export const text = {
  en: {
    home: 'Home',
    about: 'About',
    projects: 'Projects',
    contact: 'Contact',
    hero: "Hey there, I'm João, a React & Node.js enthusiast",
    viewProjects: 'View Projects',
    downloadCV: 'Download CV',
    aboutMe: 'About Me',
    softSkills: 'Soft Skills',
    technologies: 'Technologies and Languages',
    projectsTitle: 'Projects',
    contactTitle: 'Contact me',
    send: 'Send',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    emailMe: 'Email Me',
    viewOnGitHub: 'View on GitHub',
    aboutParagraph: 'I’m João Vitor, a Computer Science student experienced in full-stack development with React and Node.js. I have strong proficiency in JavaScript (ES6+), TypeScript, and MySQL/MongoDB databases. I seek roles in collaborative environments — startups or large tech firms — to deliver scalable solutions.',
    teamwork: 'Good at teamwork and collaboration',
    communication: 'Clear and effective communication',
    problemSolving: 'Able to solve real problems',
    learning: 'Always open to learning',
    project1Title: 'Sample Project 1',
    project1Desc: 'Brief description of the project.',
    project2Title: 'Sample Project 2',
    project2Desc: 'Another cool project example.',
    project3Title: 'Sample Project 3',
    project3Desc: 'Interesting project showcase.',
  },
  pt: {
    home: 'Início',
    about: 'Sobre',
    projects: 'Projetos',
    contact: 'Contato',
    hero: 'Olá, sou o João, entusiasta em React e Node.js',
    viewProjects: 'Ver Projetos',
    downloadCV: 'Baixar Currículo',
    aboutMe: 'Sobre Mim',
    softSkills: 'Competências',
    technologies: 'Tecnologias e Linguagens',
    projectsTitle: 'Projetos',
    contactTitle: 'Entre em contato comigo',
    send: 'Enviar',
    name: 'Nome',
    email: 'Email',
    message: 'Mensagem',
    emailMe: 'Enviar Email',
    viewOnGitHub: 'Ver no GitHub',
    aboutParagraph: 'Sou João Vitor, estudante de Ciência da Computação com experiência em desenvolvimento full-stack usando React e Node.js e outras tecnologias. Tenho forte domínio de JavaScript (ES6+), TypeScript e bancos de dados MySQL e MongoDB. Busco oportunidades em ambientes colaborativos — startups ou grandes empresas — para entregar soluções escaláveis.',
    teamwork: 'Facilidade com trabalho em Equipe',
    communication: 'Comunicação clara e efetiva',
    problemSolving: 'Capaz de resolver problemas reais',
    learning: 'Sempre aberto ao aprendizado',
    project1Title: 'Projeto Exemplo 1',
    project1Desc: 'Breve descrição do projeto.',
    project2Title: 'Projeto Exemplo 2',
    project2Desc: 'Outro exemplo de projeto interessante.',
    project3Title: 'Projeto Exemplo 3',
    project3Desc: 'Demonstração de projeto interessante.',
  },
};
export type TextKey = keyof typeof text.en;
export type Lang = keyof typeof text;
