export const text = {
  en: {
    home: 'Home',
    about: 'About',
    projects: 'Projects',
    contact: 'Contact',
    hero: "Hi, I'm João, a React & Node.js enthusiast",
    viewProjects: 'View Projects',
    aboutMe: 'About Me',
    softSkills: 'Soft Skills',
    technologies: 'Technologies',
    projectsTitle: 'Projects',
    contactTitle: 'Contact',
    send: 'Send',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    emailMe: 'Email Me',
    viewOnGitHub: 'View on GitHub',
  },
  pt: {
    home: 'Início',
    about: 'Sobre',
    projects: 'Projetos',
    contact: 'Contato',
    hero: 'Olá, sou João, entusiasta de React e Node.js',
    viewProjects: 'Ver Projetos',
    aboutMe: 'Sobre Mim',
    softSkills: 'Competências',
    technologies: 'Tecnologias',
    projectsTitle: 'Projetos',
    contactTitle: 'Contato',
    send: 'Enviar',
    name: 'Nome',
    email: 'Email',
    message: 'Mensagem',
    emailMe: 'Enviar Email',
    viewOnGitHub: 'Ver no GitHub',
  },
};
export type TextKey = keyof typeof text.en;
export type Lang = keyof typeof text;
